steps:
  # Step 1: Build the Docker image for Cloud Run service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/total-compiler-435917-g9/cloud-native-development', '.']

  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/total-compiler-435917-g9/cloud-native-development']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloud-native-development'
      - '--image'
      - 'gcr.io/total-compiler-435917-g9/cloud-native-development'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      
# Set IAM service account (if required)
serviceAccount: cloud-build-deployer@total-compiler-435917-g9.iam.gserviceaccount.com

timeout: '900s'
