steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/total-compiler-435917-g9/cloud-native-development', '.']

  # Step 2: Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/total-compiler-435917-g9/cloud-native-development']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloud-native-development'
      - '--image'
      - 'gcr.io/total-compiler-435917-g9/cloud-native-development'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
serviceAccount: cloud-build-deployer@total-compiler-435917-g9.iam.gserviceaccount.com
